### ISSUE TITLE
why the api is different with the open endpoint?

### ISSUE THREAD

**Issue by earth-2022** [rollkit/celestia-openrpc#150]
I am a new guy,I am confused about the DOC
here is the testnet [open endpoint](https://celestia-testnet-rpc.blacknodes.net/),api list is below,it is different from the offical DOC https://node-rpc-docs.celestia.org/?version=v0.14.1，
why they are so different?
where is the DOC about open endpoint?
I am very thankful if someone can give me some advises.

https://celestia-testnet-rpc.blacknodes.net/
![image](https://github.com/user-attachments/assets/b78c3105-4535-42df-b7d5-9633e673ebaf)

**Comment by Ferret-san** [comment]
that's a celestia core endpoint, openrpc is to communicate with a light node, which you can run [here](https://docs.celestia.org/nodes/light-node)
