### ISSUE TITLE
test: client needs auth token

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/celestia-openrpc#20]
Following up from #11 `TestDataRoundTrip` requires the client to pass a auth token, which is only available from the docker bridge container keyring. Need a way to either create a static keyring or query the container for the token.

**Comment by tuxcanfly** [comment]
Latest `testcontainers` have a way to query the container using `ForExec`:

https://golang.testcontainers.org/features/wait/exec/#match-an-exit-code-and-a-response-matcher

But unforunately their latest version has a lot of dependencies and needs several `replace` statements in `go.mod`

Another alternative is to pass a static keystore as a volume to the bridge container, however it requires adding test keystore data to the repo. Thoughts? @tzdybal

**Comment by tzdybal** [comment]
We should use `local-celestia-devnet` and then we can use `ory/dockertest` (not much deps), and exec works fine. I'm working on full unit-test-flow right now.

**Comment by tzdybal** [comment]
Already resolved on main.
