### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by tzdybal** [rollkit/celestia-openrpc#6]
To ensure compatibility of this client library tests are required. Ideal solution is to create unit-level tests utilizing [local-celestia-devnet](https://github.com/rollkit/local-celestia-devnet).

As the API is very broad, implementation should be prioritized - starting with methods that will be actually used by rollkit's `da/celestia` module.

**Comment by Manav-Aggarwal** [comment]
Closed since we have unit tests in celestia-openrpc.
