### ISSUE TITLE
Create tool to extract types from celestia-node

### ISSUE THREAD

**Issue by tzdybal** [rollkit/celestia-openrpc#7]
The goal of this library is to provide celestia-node RPC client, with minimal set of dependencies (without depending on celestia-node in particular). Currently the types are copied out of celestia-node/celestia-app/tendermint.

This solution is fragile, as any change of any type used in the RPC will cause incompatibilities, and changes are expected in next versions of celestia-node.

The process of extraction of the types should be automated.

Requirements for the tool:

- works on the source code of celestia-node
- parses code and extracts any required types
- extracts types from celestia-node and dependencies (because of cosmos-sdk, celestia-app, etc)
- generates type structure free of any external dependencies
- to simplify code generation, we should reuse as much existing code as possible, replacing types by altering imports

**Comment by nashqueue** [comment]
closing this in favor of https://github.com/rollkit/rollkit/issues/1122
